-- =====================================================================
-- RESET COMPLETO DE BANCO DE DADOS: FORÇA MÁXIMA VEDAÇÕES (SUPABASE)
-- Execute este script no SQL Editor do Supabase para aplicar a estrutura completa.
-- =====================================================================

-- 1. Limpeza de tabelas anteriores
DROP TABLE IF EXISTS public.protocol_items CASCADE;
DROP TABLE IF EXISTS public.protocols CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.seal_types CASCADE;

-- 2. Tabela de Protocolos (com ID numérico auto-incrementável + CNPJ de cliente)
CREATE TABLE public.protocols (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  client_name TEXT NOT NULL,
  client_cnpj TEXT,
  title TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  total_venda NUMERIC DEFAULT 0,
  draft_form JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Itens do Protocolo
CREATE TABLE public.protocol_items (
  id TEXT PRIMARY KEY,
  protocol_id INT NOT NULL REFERENCES public.protocols(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 1,
  unit_price NUMERIC DEFAULT 0,
  cost_price NUMERIC DEFAULT 0,
  type TEXT NOT NULL DEFAULT 'estoque',
  status TEXT NOT NULL DEFAULT 'pendente',
  oem TEXT,
  nickname TEXT,
  code TEXT,
  measurements JSONB DEFAULT '{}'::jsonb,
  supplier_prices JSONB DEFAULT '{}'::jsonb,
  chosen_supplier TEXT,
  chosen_supplier_type TEXT,
  markup_percent NUMERIC,
  sale_price NUMERIC DEFAULT 0,
  needs_approval BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Clientes Cadastrados
CREATE TABLE public.clients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  cnpj TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Tipos / Categorias de Vedações Cadastradas
CREATE TABLE public.seal_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Índices para performance
CREATE INDEX idx_protocols_status ON public.protocols(status);
CREATE INDEX idx_protocols_updated_at ON public.protocols(updated_at DESC);
CREATE INDEX idx_protocol_items_protocol_id ON public.protocol_items(protocol_id);
CREATE INDEX idx_clients_name ON public.clients(name);
CREATE INDEX idx_seal_types_name ON public.seal_types(name);

-- 7. Habilitar RLS (Row Level Security)
ALTER TABLE public.protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocol_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seal_types ENABLE ROW LEVEL SECURITY;

-- 8. Políticas de Segurança RLS
CREATE POLICY "Permitir leitura total de protocolos" ON public.protocols FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de protocolos" ON public.protocols FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de itens" ON public.protocol_items FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de itens" ON public.protocol_items FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de clientes" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de clientes" ON public.clients FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de tipos de vedações" ON public.seal_types FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de tipos de vedações" ON public.seal_types FOR ALL USING (true);

-- 9. DADOS INICIAIS (SEED)

-- Clientes Iniciais
INSERT INTO public.clients (name, cnpj) VALUES
  ('Sippel Distribuidora de Peças', '12.345.678/0001-90'),
  ('AgroMáquinas do Brasil Ltda', '98.765.432/0001-10'),
  ('Usina Hidráulica União', '45.678.912/0001-34'),
  ('Indústrias Metalúrgicas Vedafast', '11.222.333/0001-44')
ON CONFLICT (name) DO NOTHING;

-- Tipos de Vedações Iniciais (Estrito)
INSERT INTO public.seal_types (name, category) VALUES
  ('Gaxeta PU', 'Gaxeta'),
  ('O-ring Viton', 'O-ring'),
  ('Retentor Haste', 'Retentor'),
  ('Raspador NBR', 'Raspador'),
  ('Anel Guia Celeron', 'Anel Guia'),
  ('Gaxeta Chevron', 'Gaxeta'),
  ('O-ring NBR 70', 'O-ring'),
  ('Retentor Pistão', 'Retentor'),
  ('Vedação Especial PTFE', 'Vedação Especial'),
  ('Gaxeta Tipo U PU', 'Gaxeta'),
  ('Raspador Poliuretano', 'Raspador'),
  ('Anel Guia Bronze', 'Anel Guia'),
  ('Buffer NBR', 'Buffer'),
  ('O-ring Silicone', 'O-ring'),
  ('Gaxeta V-Pack', 'Gaxeta')
ON CONFLICT (name) DO NOTHING;
