-- =====================================================================
-- SCHEMA DE BANCO DE DADOS: FORÇA MÁXIMA VEDAÇÕES (SUPABASE POSTGRESQL)
-- Execute este script no SQL Editor do seu projeto Supabase.
-- =====================================================================

-- 1. Tabela de Protocolos
CREATE TABLE IF NOT EXISTS public.protocols (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  client_name TEXT NOT NULL,
  client_cnpj TEXT,
  title TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  total_venda NUMERIC DEFAULT 0,
  draft_form JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Itens do Protocolo
CREATE TABLE IF NOT EXISTS public.protocol_items (
  id TEXT PRIMARY KEY,
  protocol_id INT NOT NULL REFERENCES public.protocols(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 1,
  unit_price NUMERIC DEFAULT 0,
  cost_price NUMERIC DEFAULT 0,
  type TEXT NOT NULL DEFAULT 'estoque',
  status TEXT NOT NULL DEFAULT 'pendente',
  oem TEXT,
  nickname TEXT,
  code TEXT,
  measurements JSONB DEFAULT '{}'::jsonb,
  supplier_prices JSONB DEFAULT '{}'::jsonb,
  chosen_supplier TEXT,
  chosen_supplier_type TEXT,
  markup_percent NUMERIC,
  sale_price NUMERIC DEFAULT 0,
  needs_approval BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Clientes Cadastrados
CREATE TABLE IF NOT EXISTS public.clients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  cnpj TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Tipos de Vedações Cadastradas
CREATE TABLE IF NOT EXISTS public.seal_types (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Índices para performance
CREATE INDEX IF NOT EXISTS idx_protocols_status ON public.protocols(status);
CREATE INDEX IF NOT EXISTS idx_protocols_updated_at ON public.protocols(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_protocol_items_protocol_id ON public.protocol_items(protocol_id);
CREATE INDEX IF NOT EXISTS idx_clients_name ON public.clients(name);
CREATE INDEX IF NOT EXISTS idx_seal_types_name ON public.seal_types(name);

-- 6. Habilitar RLS (Row Level Security)
ALTER TABLE public.protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocol_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seal_types ENABLE ROW LEVEL SECURITY;

-- 7. Políticas de segurança
CREATE POLICY "Permitir leitura total de protocolos" ON public.protocols FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de protocolos" ON public.protocols FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de itens" ON public.protocol_items FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de itens" ON public.protocol_items FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de clientes" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de clientes" ON public.clients FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de tipos de vedações" ON public.seal_types FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de tipos de vedações" ON public.seal_types FOR ALL USING (true);
