-- =====================================================================
-- SCHEMA DE BANCO DE DADOS: FORÇA MÁXIMA VEDAÇÕES (SUPABASE POSTGRESQL)
-- Execute este script no SQL Editor do seu projeto Supabase.
-- =====================================================================

-- 1. Tabela de Protocolos
CREATE TABLE IF NOT EXISTS public.protocols (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  client_name TEXT NOT NULL,
  client_cnpj TEXT,
  title TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  total_venda NUMERIC DEFAULT 0,
  draft_form JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Itens do Protocolo
CREATE TABLE IF NOT EXISTS public.protocol_items (
  id TEXT PRIMARY KEY,
  protocol_id INT NOT NULL REFERENCES public.protocols(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  quantity NUMERIC NOT NULL DEFAULT 1,
  unit_price NUMERIC DEFAULT 0,
  cost_price NUMERIC DEFAULT 0,
  type TEXT NOT NULL DEFAULT 'estoque',
  status TEXT NOT NULL DEFAULT 'pendente',
  oem TEXT,
  nickname TEXT,
  code TEXT,
  brand TEXT,
  measurements JSONB DEFAULT '{}'::jsonb,
  chosen_supplier TEXT,
  chosen_supplier_type TEXT,
  supplier_id TEXT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  markup_percent NUMERIC,
  sale_price NUMERIC DEFAULT 0,
  needs_approval BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Clientes Cadastrados
CREATE TABLE IF NOT EXISTS public.clients (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  cnpj TEXT,
  bling_id BIGINT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Famílias de Vedações (Categorias Globais)
CREATE TABLE IF NOT EXISTS public.seal_families (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  bling_id BIGINT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Índices para performance
CREATE INDEX IF NOT EXISTS idx_protocols_status ON public.protocols(status);
CREATE INDEX IF NOT EXISTS idx_protocols_updated_at ON public.protocols(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_protocol_items_protocol_id ON public.protocol_items(protocol_id);
CREATE INDEX IF NOT EXISTS idx_clients_name ON public.clients(name);

-- 6. Habilitar RLS (Row Level Security)
ALTER TABLE public.protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocol_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seal_families ENABLE ROW LEVEL SECURITY;

-- 7. Políticas de segurança
CREATE POLICY "Permitir leitura total de protocolos" ON public.protocols FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de protocolos" ON public.protocols FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de itens" ON public.protocol_items FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de itens" ON public.protocol_items FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de clientes" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de clientes" ON public.clients FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de famílias" ON public.seal_families FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de famílias" ON public.seal_families FOR ALL USING (true);

-- 8. Tabela de Fornecedores
CREATE TABLE IF NOT EXISTS public.suppliers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL CHECK (type IN ('Mercado Local', 'Fornecedor Original')),
  bling_id BIGINT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabela de Configurações Globais
CREATE TABLE IF NOT EXISTS public.system_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir configurações iniciais padronizadas
INSERT INTO public.system_settings (key, value)
VALUES 
  ('markup_original', '70'::jsonb),
  ('markup_local', '30'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- Segurança das novas tabelas
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura total de fornecedores" ON public.suppliers FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de fornecedores" ON public.suppliers FOR ALL USING (true);

CREATE POLICY "Permitir leitura total de configurações" ON public.system_settings FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de configurações" ON public.system_settings FOR ALL USING (true);

-- =====================================================================
-- FASE 2: GESTÃO DE EQUIPE E PERFIS DE USUÁRIOS
-- =====================================================================

-- 11. Tabela de Perfis de Usuários (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'funcionario')),
  job_title TEXT NOT NULL,
  department TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  needs_password_change BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger para criar perfil automaticamente se um usuário for inserido em auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, job_title, department)
  VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', 'Usuário ' || split_part(new.email, '@', 1)), 
          COALESCE(new.raw_user_meta_data->>'role', 'funcionario'),
          COALESCE(new.raw_user_meta_data->>'job_title', 'Não definido'),
          COALESCE(new.raw_user_meta_data->>'department', 'Não definido'))
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Segurança da tabela profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Usuários podem ler seu próprio perfil
CREATE POLICY "Usuários podem ler o próprio perfil" ON public.profiles 
  FOR SELECT USING (auth.uid() = id);

-- Qualquer pessoa logada pode ler perfis (para ver quem fez o protocolo, etc)
CREATE POLICY "Qualquer logado pode ler perfis da empresa" ON public.profiles 
  FOR SELECT USING (auth.role() = 'authenticated');

-- Apenas admins podem atualizar os perfis (via banco)
CREATE POLICY "Admins podem atualizar perfis" ON public.profiles 
  FOR UPDATE USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- =====================================================================
-- FASE 3: ESTOQUE E PROTOCOLOS
-- =====================================================================

-- 12. Tabela de Estoque (Substitui Mock)
CREATE TABLE IF NOT EXISTS public.stock_products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT NOT NULL,
  code TEXT NOT NULL,
  stock NUMERIC NOT NULL DEFAULT 0,
  cost_price NUMERIC NOT NULL DEFAULT 0,
  category TEXT NOT NULL,
  brand TEXT,
  measurements JSONB DEFAULT '{}'::jsonb,
  bling_id BIGINT UNIQUE,
  supplier_id TEXT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Segurança da tabela stock_products
ALTER TABLE public.stock_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura total de estoque" ON public.stock_products FOR SELECT USING (true);
CREATE POLICY "Permitir inserção/atualização de estoque" ON public.stock_products FOR ALL USING (true);

-- 13. Tabela de Logs de Importa��o
CREATE TABLE IF NOT EXISTS public.import_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bling_id BIGINT,
  original_name TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.import_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura total de import_logs para admins" 
ON public.import_logs FOR SELECT 
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Permitir inser��o de import_logs" 
ON public.import_logs FOR INSERT 
WITH CHECK (true);
